# Generated by Django 4.1.5 on 2023-02-10 09:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_event_organize'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='CreatedAt',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='DateEvent',
            new_name='dateEvent',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='ImageEvent',
            new_name='imageEvent',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='NombreParticipants',
            new_name='nombreParticipants',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='State',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='UpdatedAt',
            new_name='updatedAt',
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(related_name='participations', through='events.Participation', to=settings.AUTH_USER_MODEL),
        ),
    ]
